apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # Base64 encoded "mongoadmin"
  mongo-root-password: cGFzc3dvcmQxMjM=  # Base64 encoded "password123"

