apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv-3

